---
title: "COVID-19 JHU Visualizations"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
author: "Thanks to JHU for data (https://github.com/CSSEGISandData/COVID-19)"
output:
  rmarkdown::html_document:
    theme: cosmo
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F,cache=T)
```
Based on JHU data. Results are only as good as the data, which is only as good as the amount of testing done. 

(Source code: https://github.com/b-lev/covid19-vis)

```{r init, echo=FALSE, include=FALSE}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(scales))
suppressPackageStartupMessages(library(lubridate))
suppressPackageStartupMessages(library(ggrepel))
suppressPackageStartupMessages(library(data.table))
theme_set(theme_gray(12))
theme_update(legend.position='top')
# read in JHU data
# transpose the colums/rows
# set type column to confirmed" (or deaths or recovered)
# rename columns
confirmed<- fread("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv") %>% 
	as.tbl %>%
	gather(date, val, -`Province/State`,-`Country/Region`,-Lat ,-Long) %>%
	mutate(date=mdy(date),type='confirmed') %>%
	rename('province'=`Province/State`,region=`Country/Region`)

deaths<- read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Deaths.csv") %>% 
	gather(date, val, -`Province/State`,-`Country/Region`,-Lat ,-Long) %>%
	mutate(date=mdy(date),type='deaths') %>%
	rename('province'=`Province/State`,region=`Country/Region`)

recovered<- read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Recovered.csv')%>% 
	gather(date, val, -`Province/State`,-`Country/Region`,-Lat ,-Long) %>%
	mutate(date=mdy(date),type='recovered') %>%
	rename('province'=`Province/State`,region=`Country/Region`)

# bind all rows together
covid<- bind_rows(confirmed,deaths,recovered)%>% filter(val>0) %>%
		mutate(region=ifelse(region=='Korea, South',"S.Korea",region))


# cleanup: separate out city and state. 
# Sometimes states are two-letter abbrev; sometimes full name. Make all two letters
US<- filter(covid,region=='US') %>%
	mutate(province=ifelse(str_count(province,",")>0,province,paste0(", ",province))) %>%
	separate(province,c("city",'state'),sep=", ",remove=F,fill="right") %>%
	mutate(state=ifelse(city=="",state.abb[match(state,state.name)],state))%>%
	filter(!is.na(state))

# Grab data fro each state, and ignore cruise ships
US.by_state <- group_by(US,type,date,state)%>% 
	summarize(val=sum(val)) %>%
	filter(!(state  %in% c('CA (From Diamond Princess)','NE (From Diamond Princess)','TX (From Diamond Princess)')))%>%
	group_by(type,state)%>% 
	arrange(type,state,date) %>%
	mutate(delta=val-lag(val)) 


# this is the data from JHU; see next line
ma.jhu<-filter(US.by_state,state %in% c('Massachusetts','MA'),val>=1) %>%
	mutate(val.log=log(val)) %>%
	ungroup %>% 
	mutate(rn=row_number())
```

### World data
```{r world, echo=FALSE,fig.width = 5, fig.asp = .8}

# All three lines for the world
ggplot(covid %>% 
			 	group_by(date,type) %>% 
			 	summarize(val=sum(val)))+
	aes(date,val,group=type,color=type)+
	geom_line()+geom_point()+
	scale_y_continuous(label=comma,breaks=pretty_breaks(),
										 sec.axis = sec_axis(~./7771316390,labels = percent))+
	theme(legend.position = c(.2,.8))+
	scale_x_date(breaks=pretty_breaks())+
	labs(x="",y="",color=element_blank())
```


### Country breakdown (without China)

```{r world2,fig.height=8}
######################
tmp=group_by(covid,region,type,date) %>% 
	filter(val>0,region!='China',date>='2020-02-25') %>%
	summarize(val=sum(val)) %>%
	group_by(region) %>%
	filter(max(val)>=1)
labels=group_by(tmp,region,type) %>% filter(date==max(date))  %>%
	ungroup

worst<- labels %>% 
	group_by(region) %>% 
	summarize(val=max(val)) %>% 
	top_n(6,val) %>% 
	pull(region)


ggplot(tmp)+theme_gray(12)+
	aes(date,val,group=c(region),color=region)+
	scale_y_continuous(limits = c(NA,NA),
										 # sec.axis = dup_axis()
	)+
	scale_x_date(breaks=pretty_breaks(10),limits = c(min(tmp$date),max(tmp$date)+4))+
	geom_line()+geom_point()+
	# guides(color=guide_legend(ncol=1))+
	theme(legend.position="none")+
	facet_wrap(~type,scales = 'free',ncol=2)+
	theme(legend.position="none",
				axis.text.x = element_text(angle = 90, vjust = .5))+
	labs(x="",y='count')+
	geom_text_repel(data=labels %>%	
							filter(	region %in% worst| region=='US'),
							 direction='y',segment.color='dark grey',
						hjust=0,
						aes(label=region,x=date+.2),color='black')
######################
```

### US data
```{r states, fig.height = 6, fig.width=8}

tmp<-group_by(US,state,type,date) %>% 
	summarize(val=sum(val)) %>%
	group_by(state) %>%
	filter(date>'2020-02-23')
labels<- group_by(tmp,type) %>% 
	filter(date==max(date)) %>%
	top_n(5,val)


ggplot(tmp )+
	aes(date,val,group=c(state),color=state)+
	scale_y_continuous(breaks=pretty_breaks(),
										 limits = c(0,NA),
										 # sec.axis = dup_axis()
	)+
	scale_x_date(breaks=pretty_breaks(10),
							 date_labels = "%b%d")+
	geom_line()+geom_point()+
	# guides(color=guide_legend(ncol=1))+
	theme(legend.position="none",
				axis.text.x = element_text(angle = 90, vjust = .5),
				panel.spacing = unit(2, "lines"))+
	geom_text_repel(data=labels,
									direction = 'x',
									aes(label=state,x=date+2),
									color='black')+
	facet_wrap(type~.,nrow=2,scales = 'free_y')+
	labs(x="",y='')
######################
```

# Predictions for MA, CA, and NY
```{r MA,fig.height=3,fig.width=5}
# this is the data from JHU; see next line
ma.jhu<-filter(US.by_state,state %in% c('Massachusetts','MA'),val>=1) %>%
	mutate(val.log=log(val)) %>%
	ungroup %>% 
	mutate(rn=row_number())

# data scrapped manually from mass.gov. very different than JHU
ma.gov<-suppressMessages(read_csv('MA-stats.csv'))%>%
	mutate(date=mdy(date),
				 val=confirmed+presumptive,
				 val.log=log(val),
				 rn=row_number()-2)%>% 
	mutate(delta=val-lag(val))

# plot new cases per day
# ggplot(ma.gov %>% select(date,val,delta) %>%na.omit)+
# 	aes(date,delta)+
# 	geom_bar(stat="identity")+
# 	scale_y_continuous(breaks=pretty_breaks(10))+
# 	labs(y="new cases in MA per day")

# Fit MA data to exponential 

# adjust "rn>0" to fit to different parts of the data
ma<-select(ma.gov ,date,val,val.log,rn) %>%filter(rn>=10)

lm<-with(ma,lm(val.log~rn))
fit.int<-lm$coefficients[['(Intercept)']]
fit.s<- lm$coefficients[['rn']]
fit<- tibble(rn=1:(20)) %>% 
	mutate(fit=fit.s*rn+fit.int,
				 val=exp(fit),
				 date=as.Date("2020-03-02")+rn) 

# 
# Show fit to line on log-scake
# ggplot()+
# 	geom_point(data=ma.gov ,aes(rn,val.log))+
# 	geom_abline(aes(slope=fit.s,intercept = fit.int),linetype=2)+
# 	geom_line(data=fit,aes(x=rn,y=fit),color='red')+
# 	scale_x_continuous(breaks=pretty_breaks())+
# 	scale_y_continuous(breaks=1:30)+
# 	labs(title=paste(round(fit.s,3),"*x+",round(fit.int,3)))+
# 	labs(y="confirmed (log scale)",x="day")

ggplot()+
	geom_line(data=fit,aes(x=date,y=val,color='prediction'),linetype=2)	+
	geom_point(data=fit,aes(x=date,y=val,color='prediction'))	+
	geom_point(data=ma.gov %>% filter(date>='2020-03-01'),aes(date,val,color='actual'))+
	scale_y_continuous(breaks=pretty_breaks(5),label=comma,
										 sec.axis = dup_axis())+
	scale_x_date(breaks=pretty_breaks())+
	theme(legend.position = c(.2,.8))+
	labs(y="confirmed cases in MA",x="",color=element_blank())

```

```{r CA, fig.height=3,fig.width=5}

ca.jhu<-filter(US.by_state,state %in% c('California','CA'),val>=1,date>='2020-03-01') %>%
	mutate(val.log=log(val)) %>%
	ungroup %>% 
	mutate(rn=row_number())%>% 
	filter(type=='confirmed')

lm<-with(ca.jhu,lm(val.log~rn))
fit.int<-lm$coefficients[['(Intercept)']]
fit.s<- lm$coefficients[['rn']]
fit<- tibble(rn=1:(22)) %>% 
	mutate(fit=fit.s*rn+fit.int,
				 val=exp(fit),
				 date=as.Date("2020-02-29")+rn) %>%
	filter(val<=12000000)
# 
# Show fit to line on log-scake
#ggplot()+
#	geom_point(data=ca.jhu,aes(rn,val.log))+
#	geom_abline(aes(slope=fit.s,intercept = fit.int),linetype=2)+
#	geom_line(data=fit,aes(x=rn,y=fit),color='red')+
#	scale_x_continuous(breaks=pretty_breaks())+
#	scale_y_continuous(breaks=1:20,
#										 sec.axis =sec_axis(~ exp(.),name='Continuous scale'))+
#	labs(title=paste(round(fit.s,3),"*x+",round(fit.int,3)))+
#	labs(y="confirmed (log scale)",x="day")

# Show plot and prediction 
ggplot()+
	geom_line(data=fit,aes(x=date,y=val,color='prediction'),linetype=2)	+
	geom_point(data=fit,aes(x=date,y=val,color='prediction'))	+
	geom_point(data=ca.jhu,aes(date,val,color='actual'))+
	scale_y_continuous(breaks=pretty_breaks(),label=comma,
										 sec.axis = dup_axis())+
	scale_x_date(breaks=pretty_breaks())+
	theme(legend.position = c(.3,.8))+
	labs(y="confirmed cases in CA",x="",color=element_blank())
```

```{r NY, fig.height=3,fig.width=5}
ny.jhu<-filter(US.by_state,state %in% c('New York','NY'),val>=1,date>'2020-03-07') %>%
	mutate(val.log=log(val)) %>%
	ungroup %>% 
	mutate(rn=row_number())%>% 
	filter(type=='confirmed')

lm<-with(ny.jhu,lm(val.log~rn))
fit.int<-lm$coefficients[['(Intercept)']]
fit.s<- lm$coefficients[['rn']]
fit<- tibble(rn=1:(16)) %>% 
	mutate(fit=fit.s*rn+fit.int,
				 val=exp(fit),
				 date=as.Date("2020-03-07")+rn) %>%
	filter(val<=12000000)
# 
# Show fit to line on log-scake
#ggplot()+
#	geom_point(data=ny.jhu,aes(rn,val.log))+
#	geom_abline(aes(slope=fit.s,intercept = fit.int),linetype=2)+
#	geom_line(data=fit,aes(x=rn,y=fit),color='red')+
#	scale_x_continuous(breaks=pretty_breaks())+
#	scale_y_continuous(breaks=1:20,
#										 sec.axis =sec_axis(~ exp(.),name='Continuous scale'))+
#	labs(title=paste(round(fit.s,3),"*x+",round(fit.int,3)))+
#	labs(y="confirmed (log scale)",x="day")

# Show plot and prediction 
ggplot()+
	geom_line(data=fit,aes(x=date,y=val,color='prediction'),linetype=2)	+
	geom_point(data=fit,aes(x=date,y=val,color='prediction'))	+
	geom_point(data=ny.jhu,aes(date,val,color='actual'))+
	scale_y_continuous(breaks=pretty_breaks(),label=comma,
										 sec.axis = dup_axis())+
	scale_x_date(breaks=pretty_breaks())+
	theme(legend.position = c(.3,.8))+
	labs(y="confirmed cases in NY",x="",color=element_blank())

```

## Fatality Rates

Really hard to tell whether this analysis makes sense at all given the unreliablity of the data overall. FWIW:

```{r fatality, echo=FALSE}
# fatility date
# sepaate out china
rate<- 
	inner_join(confirmed %>% group_by(date,region) %>% summarize(confirmed=sum(val)),
						 deaths %>%group_by(date,region) %>% summarize(deaths=sum(val)),
						 by = c("region", "date")) %>%
	inner_join(recovered %>%group_by(date,region) %>%	summarize(recovered=sum(val)),
						 by = c("region", "date")) %>%
	filter(region!='Cruise Ship' ) %>%
	mutate(region=ifelse(region=='Korea, South',"S.Korea",region)) %>%
	filter(deaths>0) %>% 
	mutate(rate=deaths/(deaths+confirmed)) %>%  ungroup %>% 
	rowwise %>%
	mutate(ci=1.96*sqrt(rate*(1-rate)/(deaths+confirmed))) %>%  ungroup %>% 
	group_by(region) %>% mutate(min_ci=min(ci)) %>%
	rowwise %>% 
	filter(date>'2020-02-18',min_ci<0.005,ci<.01 | (region=='US' & ci<.02))
labels=rate %>% ungroup %>% group_by(region) %>% filter(date==max(date))

ggplot(rate)+
	aes(date,rate,group=region,color=region)+
	geom_text_repel(data=labels,segment.color='dark grey',
									direction='y',
						aes(label=region,x=date+.5),					
						hjust=0,color='black')+
	geom_line()+geom_point()+
	#geom_errorbar(aes(ymax=rate+ci,ymin=rate-ci))+ 
	scale_y_continuous(label=percent,breaks=pretty_breaks(10))+
	scale_x_date(breaks=pretty_breaks(),
							 limits = c(min(rate$date),max(rate$date)+8))+
	labs(y='fatality rate',x="")+
	theme(legend.position='none')

```

Comparative Growth from ~300 cases 

```{r comaprison}

compare<- filter(covid,type %in% c('confirmed'))  %>%
	group_by(region,date,type) %>%
	summarize(val=sum(val)) %>%
	filter(val>=300) %>%
	group_by(region,type) %>%
	mutate(day=row_number())%>%
	filter( region%in% c('Italy','US','S.Korea')) %>%
	mutate(pop=ifelse(region=='Italy',  60462000,
										ifelse(region=='US',  331003000,
													 ifelse(region=='S.Korea',  51269000))))

labels<- compare %>% group_by(region) %>% filter(day==max(day)) %>%
	mutate(day=max(day,day)) 

ggplot(compare)+
	aes(day,val,group=c(region),color=region)+
	theme(legend.position = "none")+
	geom_line()+geom_point()+
	geom_text_repel(data=labels,aes(label=region),color='black',direction='x')+
	labs(y='confirmed cases')
```

```{r}
# read_csv('MA-stats.csv')
```
